# Generated by Django 2.1.4 on 2018-12-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
