# Generated by Django 2.1.4 on 2018-12-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_auto_20181214_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trips_planned', to='travel_app.User'),
            preserve_default=False,
        ),
    ]
